### ISSUE TITLE
Example code throws exception

### ISSUE THREAD

**Issue by nickponline** [pingswept/pysolar#100]
The example code from the documentation:

```
from pysolar.solar import *
import datetime

date = datetime.datetime.now()
print(get_altitude(42.206, -71.382, date))
date = datetime.datetime(2007, 2, 18, 15, 13, 1, 130320, tzinfo=datetime.timezone.utc)
print(get_altitude(42.206, -71.382, date))
```

Throws the following exception:

```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    print(get_altitude(42.206, -71.382, date))
  File "/usr/local/lib/python2.7/site-packages/pysolar/tzinfo_check.py", line 77, in func_with_check
    full = inspect.getfullargspec(func)
AttributeError: 'module' object has no attribute 'getfullargspec'
```
Python 2.7.15

**Comment by nickponline** [comment]
I see look like I should use Python 3.
