### ISSUE TITLE
get_altitude_fast and get_altitude error with same inputs

### ISSUE THREAD

**Issue by catafest** [pingswept/pysolar#50]
What is wrong with this functions? See my example:

```
>>> from pysolar.solar import *
>>> import datetime
>>> my_data = datetime.datetime.now()
>>> print my_data
2017-04-20 19:21:09.478130
>>> get_altitude_fast(47.4616,26.3015,datetime.datetime.now())
-20.114173501280593
>>> get_altitude_fast(47.4616,26.3015,my_data)
-20.352695547467164
>>> get_altitude(47.4616,26.3015,my_data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pysolar/solar.py", line 58, in get_altitude
    jd = time.get_julian_solar_day(when)
  File "/usr/lib/python2.7/site-packages/pysolar/time.py", line 742, in get_julian_solar_day
    +
AttributeError: 'datetime.datetime' object has no attribute 'timestamp' 
```

**Comment by pingswept** [comment]
From http://docs.pysolar.org/en/latest/#troubleshooting

"If you find yourself getting errors like AttributeError: ‘datetime.datetime’ object has no attribute ‘timestamp’, this probably means that you are using Python 2 instead of Python 3."
